changes necessary to enable the correct extras repo on rhel 7/8
reynencourt/kubespray pull request #28
Opened 2021-03-29 18:44 UTC by bodanc

2021-03-29 18:46 UTC, bodanc commented
https://reynencourt.atlassian.net/browse/PD-156

testing done; all good;

2021-03-30 08:03 UTC, r3dsm0k3 requested changes
@bodanc There's some code I see as commented out. We should _remove_ it if it is not needed to achieve cleanliness. Comments does not add any value in this case. Git always preserves the history, so even in the case you want to refer later you can always go back and check it.

2021-03-30 08:03 UTC, r3dsm0k3 commented on roles/container-engine/containerd/defaults/main.yml
> +#extras_repo_gpgkey: "http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-7"
Can you remove the commented out code if it is not needed?

2021-03-30 08:03 UTC, r3dsm0k3 commented on roles/container-engine/containerd/tasks/containerd_repo.yml
> +#- name: check if container-selinux is available
Can you remove the commented out code?

2021-03-30 15:56 UTC, merged